import os
import pandas as pd
import anndata as ad
import numpy as np
import shutil
from sklearn.metrics import adjusted_rand_score, rand_score, f1_score

from STHD.sthdio import STHD
from STHD import patchify, train


def evaluate_sthd_dictionary(adata_base, outdir, beta=1.0):
    """Loads a saved mu dictionary, runs STHD, and returns Total/Clean/Mixed Metrics."""
    
    # 1. Load the pristine dictionary generated by the VGAE ablation
    dict_path = os.path.join(outdir, "profiles.tsv")
    if not os.path.exists(dict_path):
        print(f"Skipping {outdir} - No profiles.tsv found.")
        return None
        
    vgae_profiles = pd.read_csv(dict_path, sep='\t', index_col=0)
    cell_type_names = vgae_profiles.columns.tolist()
    
    print(f"\n{'-'*70}")
    print(f"Evaluating Dictionary from {outdir.split('/')[-1]} | Clusters: {len(cell_type_names)}")

    # 2. Initialize STHD
    sthd_data = STHD(adata_base.copy(), load_type="anndata")
    sthd_data.lambda_cell_type_by_gene_matrix = vgae_profiles.values.T 

    # 3. Patchify
    sthd_out = os.path.join(outdir, "sthd_tmp")
    if os.path.exists(sthd_out): shutil.rmtree(sthd_out)
    
    patchify.patchify(sthd_data, save_path=sthd_out, max_cells=5000, halo=50.0)
    patch_dir = os.path.join(sthd_out, "patches")
    patch_files = [os.path.join(patch_dir, f) for f in os.listdir(patch_dir)]

    # 4. Train STHD on Patches
    print(f"Running STHD EM Loop on {len(patch_files)} patches...")
    
    # FIX: Create a safe dictionary to hold confidences outside of STHD's memory
    global_confidences = {}  
    
    for patch_path in patch_files:
        sthdata = train.load_data(patch_path)
        sthdata.lambda_cell_type_by_gene_matrix = vgae_profiles.values.T
        
        # Core STHD Optimization returns probability matrix P_ct
        P_ct = train.train(sthdata, n_iter=30, step_size=0.5, beta=beta, anisotropic=True)
        
        # FIX: Extract max confidence and store by the exact cell ID
        P_array = np.array(P_ct) 
        max_probs = np.max(P_array, axis=1)
        for cid, prob in zip(sthdata.adata.obs_names, max_probs):
            global_confidences[cid] = prob
        
        # Predict and save
        sthdata = train.predict(sthdata, P_ct, cell_type_names)
        train.save_prediction_pdata(sthdata, file_path=patch_path)

    # 5. Merge Patches Back Together
    patchify.merge(save_path=sthd_out, refile=dict_path)
    adata_final = train.load_data_with_pdata(os.path.join(sthd_out, "all_region")).adata

    # FIX: Restore the confidences directly to the final dataframe using the cell IDs
    adata_final.obs['STHD_confidence'] = adata_final.obs_names.map(global_confidences).fillna(0)

    # Map predictions to Ground Truth labels
    mapping = pd.crosstab(adata_final.obs["STHD_pred_ct"], adata_final.obs["Cell Type"]).idxmax(axis=1).to_dict()
    adata_final.obs["Mapped_STHD"] = adata_final.obs["STHD_pred_ct"].map(mapping)

    # 6. CALCULATE CONFIDENCE TO SPLIT CLEAN VS MIXED
    clean_mask = adata_final.obs['STHD_confidence'] >= 0.80  # 80% confident
    mixed_mask = adata_final.obs['STHD_confidence'] < 0.80   # Less than 80% confident

    # Helper function to calculate metrics safely on subsets
    def calc_metrics_on_subset(mask):
        if np.sum(mask) == 0: return 0, 0, 0
        a = adjusted_rand_score(adata_final.obs['Cell Type'][mask], adata_final.obs['Mapped_STHD'][mask])
        r = rand_score(adata_final.obs['Cell Type'][mask], adata_final.obs['Mapped_STHD'][mask])
        f = f1_score(adata_final.obs['Cell Type'][mask], adata_final.obs['Mapped_STHD'][mask], average='weighted')
        return a, r, f

    ari_tot, ri_tot, f1_tot = calc_metrics_on_subset(np.ones(len(adata_final), dtype=bool))
    ari_cln, ri_cln, f1_cln = calc_metrics_on_subset(clean_mask)
    ari_mix, ri_mix, f1_mix = calc_metrics_on_subset(mixed_mask)
    
    print("\n  === METRICS BREAKDOWN ===")
    print(f"  [TOTAL] Cells: {len(adata_final):<7} | ARI: {ari_tot:.4f} | F1: {f1_tot:.4f}")
    print(f"  [CLEAN] Cells: {np.sum(clean_mask):<7} | ARI: {ari_cln:.4f} | F1: {f1_cln:.4f}  (Confidence >= 80%)")
    print(f"  [MIXED] Cells: {np.sum(mixed_mask):<7} | ARI: {ari_mix:.4f} | F1: {f1_mix:.4f}  (Confidence < 80%)")
    
    # 7. Append to results text file
    res_file = os.path.join(outdir, "results.txt")
    with open(res_file, "a") as f:
        f.write(f"STHD [TOTAL] ARI: {ari_tot:.4f} | [CLEAN] ARI: {ari_cln:.4f} | [MIXED] ARI: {ari_mix:.4f}\n")
            
    return ari_tot, f1_tot, ari_cln, f1_cln

if __name__ == "__main__":
    # --- 1. LOAD BASE DATA ---
    print("Loading B004 Ground Truth Data...")
    df_HuBMAP = pd.read_csv('/hpc/group/yizhanglab/vk93/sthd-codex/data/23_09_CODEX_HuBMAP_alldata_Dryad_merged.csv', index_col=0)
    marker_cols = ['MUC2', 'SOX9', 'MUC1', 'CD31', 'Synapto', 'CD49f', 'CD15', 'CHGA', 'CDX2', 'ITLN1', 'CD4', 'CD127', 'Vimentin', 'HLADR', 'CD8', 'CD11c', 'CD44', 'CD16', 'BCL2', 'CD3', 'CD123', 'CD38', 'CD90', 'aSMA', 'CD21', 'NKG2D', 'CD66', 'CD57', 'CD206', 'CD68', 'CD34', 'aDef5', 'CD7', 'CD36', 'CD138', 'CD45RO', 'Cytokeratin', 'CD117', 'CD19', 'Podoplanin', 'CD45', 'CD56', 'CD69', 'Ki67', 'CD49a', 'CD163', 'CD161']

    df_sub = df_HuBMAP[df_HuBMAP['donor'] == 'B004'] 
    adata = ad.AnnData(X=df_sub[marker_cols].values, obs=df_sub.drop(columns=marker_cols))
    adata.var_names = marker_cols
    adata.obsm['spatial'] = df_sub[['x', 'y']].values
    
    # --- 2. LOOP THROUGH ABLATION DIRECTORIES ---
    ablations = [
        "/hpc/home/vk93/lab_vk93/sthd-codex/sthd_ct_intestine_v0/mu_dict_knn_gat_ablations/ablation_knn_gcn",
        "/hpc/home/vk93/lab_vk93/sthd-codex/sthd_ct_intestine_v0/mu_dict_knn_gat_ablations/ablation_mknn_gcn",
        "/hpc/home/vk93/lab_vk93/sthd-codex/sthd_ct_intestine_v0/mu_dict_knn_gat_ablations/ablation_snn_gcn",
        "/hpc/home/vk93/lab_vk93/sthd-codex/sthd_ct_intestine_v0/mu_dict_knn_gat_ablations/ablation_knn_gat",
        "/hpc/home/vk93/lab_vk93/sthd-codex/sthd_ct_intestine_v0/mu_dict_knn_gat_ablations/ablation_mknn_gat"
    ]
    
    results = {}
    for folder in ablations:
        metrics = evaluate_sthd_dictionary(adata.copy(), folder, beta=1.0)
        if metrics is not None:
            ari_t, f1_t, ari_c, f1_c = metrics
            results[folder.split('/')[-1]] = (ari_t, f1_t, ari_c, f1_c)
            
    # --- 3. FINAL SUMMARY ---
    print("\n" + "="*80)
    print("FINAL STHD ARI LEADERBOARD (Sorted by Total ARI):")
    # Sort dictionary by ARI descending
    sorted_res = sorted(results.items(), key=lambda item: item[1][0], reverse=True)
    for name, metrics in sorted_res:
        print(f"{name:<25}: [TOTAL] ARI={metrics[0]:.4f} | [CLEAN] ARI={metrics[2]:.4f}")
    print("="*80)